[tool.poetry]
name = "habushu_mixology"
version = "0.1.0"
description = "Example of how to use the habushu-maven-plugin"
authors = ["Your Name <you@example.com>"]
license = "MIT License"

[tool.poetry.dependencies]
python = "3.9.9"

[tool.poetry.dev-dependencies]
black = "^22.3.0"
behave = "^1.2.6"
krausening-python = {path = "existing-habushu-dependencies/krausening_python-10.0.0-py3-none-any.whl"}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
