# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Build Habushu

on:
    push:
        branches: [ "dev" ]
    pull_request_target:
        branches: [ "dev" ]

jobs:
    build:

        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v4
            - name: Install Python # use direct install rather than pyenv for CI for large speed improvement
              uses: actions/setup-python@v5
              with:
                python-version: '3.11.4'

            - name: Load cached Poetry installation
              id: cached-poetry
              uses: actions/cache@v4
              with:
                path: ~/.local
                key: poetry-0  # increment to reset cache

            - name: Install Poetry
              if: steps.cached-poetry.outputs.cache-hit != 'true'
              uses: snok/install-poetry@v1

            - name: Set up JDK 11
              uses: actions/setup-java@v4
              with:
                  java-version: '11'
                  distribution: 'temurin'
                  cache: maven

            - name: Build habushu-maven-plugin
              run: mvn -B install -Pbootstrap --file pom.xml 

            - name: Test habushu-maven-plugin
              run: mvn -B install --file pom.xml -Dhabushu.usePyenv=false
